num_al_iter: 10
label_k: 1000
init_num_labeled: 1429
update_validation_set: false
seeds: [1, 2, 3, 4, 5]
measure_calibration: false
settings:
  device: cuda
  mcmd_num_trials: 5
deterministic_settings:
  cudnn_deterministic : True
  cudnn_benchmark : False
  disable_debug_apis: True
