experiment_name: aaf_double_poisson
random_seed: 1998
head_type: double_poisson
dataset:
  type: image
  spec: aaf
training:
  accelerator: gpu
  batch_size: 32
  chkp_dir: chkp
  chkp_freq: 200
  num_epochs: 200
  precision: bf16-mixed
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 200
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
